/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData lightbulb = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
